name: Run tests using playwright+pytest, generate allure report and make a notification to Slack

on:
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up the latest version of Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.x"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install --system
            playwright install chromium

        - name: Run tests
          run: pytest
          continue-on-error: true

        - name: Allure Report action from marketplace
          uses: simple-elf/allure-report-action@master
          if: always()
          with:
            allure_results: reports
            allure_history: allure-history
            keep_reports: 5

        - name: Deploy Report to Github Pages
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-history

        - name: Notify Slack Action
          uses: ravsamhq/notify-slack-action@v2
          if: always()
          with:
            status: ${{ job.status }}
           # notification_title: "{workflow} has {status_message}"
            message_format: ${{ secrets.GH_ACTIONS_URL }}
            notify_when: "success,failure"
          env:
            SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
